# Generated by Django 5.0.7 on 2024-07-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0002_alter_questao_enunciado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='gabarito',
            field=models.CharField(max_length=100),
        ),
    ]
